version: '3'

services:
  my_app:
    image: "ashraftheminhaj/ip-fetcher:${TAG}"
    container_name: my_app
    ports:
      - "8080:8080"

  # monitor:
  #   tty: true
  #   image: ashraftheminhaj/pydonitor
  #   container_name: pydonitor
  #   environment:
  #     - container_name=my_app
  #     - discord_webhook_url=https://custom/webhook
  #   depends_on:
  #     - my_app
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - "6379:6379"
